### ISSUE TITLE
More navigation/layout options

### ISSUE THREAD

**Issue by thejaff2** [joadan/TabBlazor#6]
Hi, and great work!

I was wondering when/if you will get to more layout options? Preferably dark mode with horizontal sticky header :) (Sorry if I missed something when looking at the code).

**Comment by joadan** [comment]
Hi,

I haven't investigated dark mode in detail, but the principal is just to set the class "theme-dark" on the body.
I tried it on the demo page and it doesn't work 100% due to some custom css TabBlazor is using and the fact that the demo page is not designed for dark mode. That is something we should be able to fix.

For the layout options, the NavBar blazor component is only for left menu at this point, but you should fairly easy just be able to make you own component using the html from the Tabler sample as a starting point, or if you are up to it provide a PR. 
I have on the things to do to provide a more generic Navbar but I'm afraid it's not a high priority, also there are som many options so it could be better just to roll your own and have full control.

**Comment by thejaff2** [comment]
Fair enough. I'm new to Blazor but I'll see what I can do.

**Comment by joadan** [comment]
Welcome to Blazor!

I'll try to add an option in the samples to toogle dark mode, so we can try it out.
If I have time I also try to add a sample with different layout options.

**Comment by joadan** [comment]
I added a DarkMode toogle to the demo site.

**Comment by thejaff2** [comment]
Great! I'll take a look.

**Comment by joadan** [comment]
I have now added some options for layout, please check out [Settings](https://tabblazor.com/app-settings)

**Comment by joadan** [comment]
Fixed in v0.4.4-alpha
